

sequences: "profiles/dmsa-phenotype/data/12y_sequences.fasta.xz"
metadata: "profiles/dmsa-phenotype/data/12y_metadata.tsv.xz"

custom_rules:
  - profiles/dmsa-phenotype/dmsa-pred/dmsa_rules.smk

fasta_fields:
  - strain

lat-longs: "config/lat_longs.tsv"

segments:
  - ha

tree:
  tree-builder-args: "'-ninit 10 -n 4 -czb'"

submission_date_field: date_submitted
recency:
  date_bins: [7, 30, 90]
  date_bin_labels: ["last week", "last month", "last quarter"]
  upper_bin_label: older

# DMSA phenotype prediction
# dictionary of phenotype collections
# each collection has a name and a set of parameters
# For a number of individual experiemnts.
dmsa_phenotype_collections:
  all-sera:
    # name of the wildtype sequence strain - must be included in sequences
    dms_wt_seq_id: "A/HK/45/2019"
    # directory containing escape csv's
    mut_effects_dir: "profiles/dmsa-phenotype/data/filtered_data/"
    # name of the column containing the effect score
    mut_effect_col: "escape_median"
    # name of the column containing the mutation
    mutation_col: "mutation"
    allow_unmeasured_aa_subs_at_these_sites: "profiles/dmsa-phenotype/data/allow_unmeasured_aa_subs_at_these_sites.txt"

builds:

    "flu_seasonal_h3n2_12y":

      lineage: h3n2
      reference: "config/h3n2/{segment}/reference.fasta"
      annotation: "config/h3n2/{segment}/genemap.gff"
      tree_exclude_sites: "config/h3n2/{segment}/exclude-sites.txt"
      clades: "config/h3n2/ha/clades.tsv"
      min_date: "100Y"
      auspice_config: "config/h3n2/auspice_config.json"
      enable_titer_models: false
      enable_lbi: true
      enable_glycosylation: true
      titer_collections:
        - name: cdc_cell_fra
          data: "example_data/cdc_h3n2_cell_fra_titers.tsv"
      subsamples:
        global:
            filters: "--exclude-where 'ha!=True'"
      # specify the collection of experiments you'd like to estimate phenotypes with.
      dmsa_phenotype:
        - "all-sera"